// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: bobo_interaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType    int32                  `protobuf:"varint,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 1-帖子 2-评论
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_bobo_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *LikeRequest) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

type LikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	mi := &file_bobo_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *LikeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType    int32                  `protobuf:"varint,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeRequest) Reset() {
	*x = UnlikeRequest{}
	mi := &file_bobo_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeRequest) ProtoMessage() {}

func (x *UnlikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeRequest.ProtoReflect.Descriptor instead.
func (*UnlikeRequest) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *UnlikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *UnlikeRequest) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

type UnlikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeResponse) Reset() {
	*x = UnlikeResponse{}
	mi := &file_bobo_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeResponse) ProtoMessage() {}

func (x *UnlikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeResponse.ProtoReflect.Descriptor instead.
func (*UnlikeResponse) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *UnlikeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 0表示一级评论，非0表示回复
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_bobo_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCommentRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type CommentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId          int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId          int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username        string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ParentId        int64                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ReplyToUserId   int64                  `protobuf:"varint,7,opt,name=reply_to_user_id,json=replyToUserId,proto3" json:"reply_to_user_id,omitempty"`
	ReplyToUsername string                 `protobuf:"bytes,8,opt,name=reply_to_username,json=replyToUsername,proto3" json:"reply_to_username,omitempty"`
	LikeCount       int64                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_bobo_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *CommentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentInfo) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentInfo) GetReplyToUserId() int64 {
	if x != nil {
		return x.ReplyToUserId
	}
	return 0
}

func (x *CommentInfo) GetReplyToUsername() string {
	if x != nil {
		return x.ReplyToUsername
	}
	return ""
}

func (x *CommentInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentInfo           `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_bobo_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCommentResponse) GetComment() *CommentInfo {
	if x != nil {
		return x.Comment
	}
	return nil
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_bobo_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *DeleteCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_bobo_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_bobo_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *GetCommentsRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetCommentsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentInfo         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_bobo_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommentsResponse) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetLikeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetIds     []int64                `protobuf:"varint,2,rep,packed,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	TargetType    int32                  `protobuf:"varint,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeStatusRequest) Reset() {
	*x = GetLikeStatusRequest{}
	mi := &file_bobo_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeStatusRequest) ProtoMessage() {}

func (x *GetLikeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetLikeStatusRequest) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *GetLikeStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLikeStatusRequest) GetTargetIds() []int64 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *GetLikeStatusRequest) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

type LikeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IsLiked       bool                   `protobuf:"varint,2,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeStatus) Reset() {
	*x = LikeStatus{}
	mi := &file_bobo_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeStatus) ProtoMessage() {}

func (x *LikeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeStatus.ProtoReflect.Descriptor instead.
func (*LikeStatus) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *LikeStatus) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *LikeStatus) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type GetLikeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*LikeStatus          `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeStatusResponse) Reset() {
	*x = GetLikeStatusResponse{}
	mi := &file_bobo_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeStatusResponse) ProtoMessage() {}

func (x *GetLikeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobo_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetLikeStatusResponse) Descriptor() ([]byte, []int) {
	return file_bobo_interaction_proto_rawDescGZIP(), []int{13}
}

func (x *GetLikeStatusResponse) GetStatuses() []*LikeStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_bobo_interaction_proto protoreflect.FileDescriptor

const file_bobo_interaction_proto_rawDesc = "" +
	"\n" +
	"\x16bobo_interaction.proto\x12\x0einteraction.v1\"d\n" +
	"\vLikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\x05R\n" +
	"targetType\"(\n" +
	"\fLikeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"f\n" +
	"\rUnlikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\x05R\n" +
	"targetType\"*\n" +
	"\x0eUnlikeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x7f\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\"\xb5\x02\n" +
	"\vCommentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\x12'\n" +
	"\x10reply_to_user_id\x18\a \x01(\x03R\rreplyToUserId\x12*\n" +
	"\x11reply_to_username\x18\b \x01(\tR\x0freplyToUsername\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x03R\tlikeCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"N\n" +
	"\x15CreateCommentResponse\x125\n" +
	"\acomment\x18\x01 \x01(\v2\x1b.interaction.v1.CommentInfoR\acomment\"N\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"^\n" +
	"\x12GetCommentsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"d\n" +
	"\x13GetCommentsResponse\x127\n" +
	"\bcomments\x18\x01 \x03(\v2\x1b.interaction.v1.CommentInfoR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"o\n" +
	"\x14GetLikeStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x02 \x03(\x03R\ttargetIds\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\x05R\n" +
	"targetType\"D\n" +
	"\n" +
	"LikeStatus\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x19\n" +
	"\bis_liked\x18\x02 \x01(\bR\aisLiked\"O\n" +
	"\x15GetLikeStatusResponse\x126\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1a.interaction.v1.LikeStatusR\bstatuses2\x8b\x04\n" +
	"\vInteraction\x12A\n" +
	"\x04Like\x12\x1b.interaction.v1.LikeRequest\x1a\x1c.interaction.v1.LikeResponse\x12G\n" +
	"\x06Unlike\x12\x1d.interaction.v1.UnlikeRequest\x1a\x1e.interaction.v1.UnlikeResponse\x12\\\n" +
	"\rCreateComment\x12$.interaction.v1.CreateCommentRequest\x1a%.interaction.v1.CreateCommentResponse\x12\\\n" +
	"\rDeleteComment\x12$.interaction.v1.DeleteCommentRequest\x1a%.interaction.v1.DeleteCommentResponse\x12V\n" +
	"\vGetComments\x12\".interaction.v1.GetCommentsRequest\x1a#.interaction.v1.GetCommentsResponse\x12\\\n" +
	"\rGetLikeStatus\x12$.interaction.v1.GetLikeStatusRequest\x1a%.interaction.v1.GetLikeStatusResponseB\x17Z\x15interaction/api/protob\x06proto3"

var (
	file_bobo_interaction_proto_rawDescOnce sync.Once
	file_bobo_interaction_proto_rawDescData []byte
)

func file_bobo_interaction_proto_rawDescGZIP() []byte {
	file_bobo_interaction_proto_rawDescOnce.Do(func() {
		file_bobo_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bobo_interaction_proto_rawDesc), len(file_bobo_interaction_proto_rawDesc)))
	})
	return file_bobo_interaction_proto_rawDescData
}

var file_bobo_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_bobo_interaction_proto_goTypes = []any{
	(*LikeRequest)(nil),           // 0: interaction.v1.LikeRequest
	(*LikeResponse)(nil),          // 1: interaction.v1.LikeResponse
	(*UnlikeRequest)(nil),         // 2: interaction.v1.UnlikeRequest
	(*UnlikeResponse)(nil),        // 3: interaction.v1.UnlikeResponse
	(*CreateCommentRequest)(nil),  // 4: interaction.v1.CreateCommentRequest
	(*CommentInfo)(nil),           // 5: interaction.v1.CommentInfo
	(*CreateCommentResponse)(nil), // 6: interaction.v1.CreateCommentResponse
	(*DeleteCommentRequest)(nil),  // 7: interaction.v1.DeleteCommentRequest
	(*DeleteCommentResponse)(nil), // 8: interaction.v1.DeleteCommentResponse
	(*GetCommentsRequest)(nil),    // 9: interaction.v1.GetCommentsRequest
	(*GetCommentsResponse)(nil),   // 10: interaction.v1.GetCommentsResponse
	(*GetLikeStatusRequest)(nil),  // 11: interaction.v1.GetLikeStatusRequest
	(*LikeStatus)(nil),            // 12: interaction.v1.LikeStatus
	(*GetLikeStatusResponse)(nil), // 13: interaction.v1.GetLikeStatusResponse
}
var file_bobo_interaction_proto_depIdxs = []int32{
	5,  // 0: interaction.v1.CreateCommentResponse.comment:type_name -> interaction.v1.CommentInfo
	5,  // 1: interaction.v1.GetCommentsResponse.comments:type_name -> interaction.v1.CommentInfo
	12, // 2: interaction.v1.GetLikeStatusResponse.statuses:type_name -> interaction.v1.LikeStatus
	0,  // 3: interaction.v1.Interaction.Like:input_type -> interaction.v1.LikeRequest
	2,  // 4: interaction.v1.Interaction.Unlike:input_type -> interaction.v1.UnlikeRequest
	4,  // 5: interaction.v1.Interaction.CreateComment:input_type -> interaction.v1.CreateCommentRequest
	7,  // 6: interaction.v1.Interaction.DeleteComment:input_type -> interaction.v1.DeleteCommentRequest
	9,  // 7: interaction.v1.Interaction.GetComments:input_type -> interaction.v1.GetCommentsRequest
	11, // 8: interaction.v1.Interaction.GetLikeStatus:input_type -> interaction.v1.GetLikeStatusRequest
	1,  // 9: interaction.v1.Interaction.Like:output_type -> interaction.v1.LikeResponse
	3,  // 10: interaction.v1.Interaction.Unlike:output_type -> interaction.v1.UnlikeResponse
	6,  // 11: interaction.v1.Interaction.CreateComment:output_type -> interaction.v1.CreateCommentResponse
	8,  // 12: interaction.v1.Interaction.DeleteComment:output_type -> interaction.v1.DeleteCommentResponse
	10, // 13: interaction.v1.Interaction.GetComments:output_type -> interaction.v1.GetCommentsResponse
	13, // 14: interaction.v1.Interaction.GetLikeStatus:output_type -> interaction.v1.GetLikeStatusResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_bobo_interaction_proto_init() }
func file_bobo_interaction_proto_init() {
	if File_bobo_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bobo_interaction_proto_rawDesc), len(file_bobo_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bobo_interaction_proto_goTypes,
		DependencyIndexes: file_bobo_interaction_proto_depIdxs,
		MessageInfos:      file_bobo_interaction_proto_msgTypes,
	}.Build()
	File_bobo_interaction_proto = out.File
	file_bobo_interaction_proto_goTypes = nil
	file_bobo_interaction_proto_depIdxs = nil
}
