apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: bobo-forum
  labels:
    app: post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post
          image: bobo-forum/post:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bobo-forum-config
                  key: post-service-port
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 5
