apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: bobo-forum
  labels:
    app: search-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search
          image: bobo-forum/search:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bobo-forum-config
                  key: search-service-port
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 5
