// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package authclient

import (
	"context"

	"auth/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest    = auth.LoginRequest
	LoginResponse   = auth.LoginResponse
	RegisterRequest = auth.RegisterRequest
	UserInfo        = auth.UserInfo

	Auth interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

func (m *defaultAuth) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultAuth) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
